### ISSUE TITLE
Is it a good idea to expose Executor in public API?

### ISSUE THREAD

**Issue by nazar-pc** [stjepang/async-executor#11]
This is a question, but I hope asking it here would be useful to other people to find whether it fits the use case.

I'm building a library which has to do some async work (like background processing, async cleanup in `Drop::drop()` that doesn't necessarily have to block its call), but I don't want to pull heavier dependencies like `async-std`, `tokio` or even `smol`.

I ended up with API that can either create `async_executor::Executor` and run on background thread or expects one to be provided explicitly:
https://github.com/nazar-pc/mediasoup/blob/ee38b3ad9bbad8638d57350902992ee2e3760073/rust/src/worker_manager.rs#L53-L89

Is this a good idea in general to expose `async_executor::Executor` as a public API of the library in this way?

I see it is used completely internally in `nats` crate, but it felt like a good idea to have an option to provide it in case there is already an executor available, potentially running on multiple threads so there is no need to create yet another thread.

**Comment by stjepang** [comment]
That seems fine to me. There isn't an established or widely accepted pattern yet because `async-executor` is still pretty new and async rust is constantly in flux. For what it's worth, `async-executor` is at v1.x so you can assume it will be stable for a long time.

**Comment by nazar-pc** [comment]
Thanks, that works for me :slightly_smiling_face:
