### ISSUE TITLE
Infinite loop stops yielding at some point

### ISSUE THREAD

**Issue by rsignavong** [stjepang/async-executor#5]
Hello,

I was trying to understand how the Executor and LocalExecutor are working by running some easy examples, but I think there is an issue.

The following code doesn't loop forever, it prints a bunch of times and stops running.

```rust
use async_executor::Executor;
use easy_parallel::Parallel;
use smol::future::yield_now;
use std::thread::sleep;
use std::time::Duration;

fn main() {
    let ex = Executor::new();
    Parallel::new()
        .each(0..4, |i| {
            ex.spawn(async move {
                let mut j = 0;
                loop {
                    j += 1;
                    println!("{}: Hello, world! {}", i, j);
                    yield_now().await;
                }
            })
            .detach();
            ex.run(yield_now());
        })
        .run();
    sleep(Duration::from_secs(10));
}
```

Moreover, I tried to add a Timer instead of `yield_now` and it only prints 4 times and stops running.
```rust
use async_executor::Executor;
use easy_parallel::Parallel;
use smol::future::yield_now;
use smol::Timer;
use std::thread::sleep;
use std::time::Duration;

fn main() {
    let ex = Executor::new();
    Parallel::new()
        .each(0..4, |i| {
            ex.spawn(async move {
                let mut j = 0;
                loop {
                    j += 1;
                    println!("{}: Hello, world! {}", i, j);
                    Timer::new(Duration::from_millis(200)).await;
                }
            })
            .detach();
            ex.run(yield_now());
        })
        .run();
    sleep(Duration::from_secs(10));
}
```

Do you know what is happening?

**Comment by stjepang** [comment]
Ah yes, that's completely normal :)

Note that the `Executor::run()` function doesn't run until all tasks have been processed - it only runs until the main future passed to it completes. So if you do `ex.run(yield_now())`, then some tasks will be run but then as soon as `yield_now()` completes, the whole `run()` stops.

At that point, you can call `run()` again with a new future if you want.

**Comment by rsignavong** [comment]
Okay I see, does it means that the main future controls all the runtime of the others tasks spawned inside the executor?
So if I give a Timer of 1 hour, it will run all spawned tasks for 1 hour, if I give an unresolved future then it will run forever?

**Comment by stjepang** [comment]
The `run()` function runs the main future. When the main future is idle (because it's waiting for I/O or timers or something), it runs other tasks on the executor. When the main future is done, it exists.

If you don't call `run()` at all, spawned tasks will simply be waiting in the executor's task queue.

If you give the main future a timer of 1 hour, it will run spawned tasks for 1 hour and then stop everything.

If you give it an unresolved future, it will run forever.

**Comment by rsignavong** [comment]
Okay got it! :)
It’s more clear now, thank you! 👍
I close the issue. ;)
